service: tenics-bot # NOTE: update this with your service name

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: 'eu-west-1'

  #give lambdas access to DynamoDB
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  findBook:
    handler: books.findBook
    memorySize: 256
  createBook:
    handler: books.create
    memorySize: 256
    events:
      - http:
          path: books
          method: post
          cors: true
  getBook:
    handler: books.getBook
    memorySize: 256
    events:
      - http:
        path: books/{id}
        method: get
        cors: true
  createRoom:
    handler: room.createRoom
    memorySize: 256
  addBookToRoom:
    handler: room.addBookToRoom
    memorySize: 256
